name: Upstream dependent feature branch

on:
  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dependents: 
          # Dependents need the repo name, the name of the workflow yaml file, and the main/master ref
          - repo: domtronn/pong
            workflow: auto-feature-branch.yml
            ref: main
  
    steps:
      - uses: actions/checkout@v2

      - id: ref
        run: |
          echo "::set-output name=branch::$(echo $GITHUB_REF | sed 's/refs\/heads\///g')"
          echo "::set-output name=feature::$(echo $GITHUB_REF | sed 's/refs\/heads\///g' | xargs -I {} echo ping/{})"
        
      - name: Dispatch Branch Deployment event
        # This needs a Basic auth PAT e.g. user:token
        run: |
          curl -X POST https://api.github.com/repos/${{ matrix.dependents.repo }}/actions/workflows/${{ matrix.dependents.workflow }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.BASIC_AUTH_PAT }} \
          --data '{ "ref": "${{ matrix.dependents.ref }}", "inputs": { "branch": "${{ steps.ref.outputs.branch }}", "sha": "'"$GITHUB_SHA"'", "feature": "${{ steps.ref.outputs.feature }}" } }'
