name: Upstream dependent feature branch

on:
  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dependents: 
          - repo: domtronn/pong
            workflow: auto-feature-branch.yml
            ref: main
  
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - id: ref
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | sed 's/refs\/heads\///g')"
        
      - name: Dispatch Branch Deployment event
        run: |
          curl -X POST https://api.github.com/repos/${{ matrix.dependents.repo }}/actions/workflows/${{ matrix.dependents.workflow }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.BASIC_AUTH_PAT }} \
          --data '{ "ref": "${{ matrix.dependents.ref }}", "inputs": { "branch": "${{ steps.ref.outputs.branch }}", "sha": "'"$GITHUB_SHA"'" } }'
